name: JAVA CI
on: push
jobs:
  clone:
    name: Clone down
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Upload repo
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .
  build:
    name: Build
    needs: [clone]
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download repo
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
      - name: Build the app
        run: chmod +x ci/build-app.sh && ci/build-app.sh
  test:
    name: Test
    needs: [clone]
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download repo
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
      - name: Run tests
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
