name: JAVA CI
on: push
env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Build the app
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Build upload
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .
  docker:
    name: Docker
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Download repo
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
      - name: Build docker
        run: chmod +x ci/build-docker.sh && ci/build-docker.sh
      - name: Push docker
        run: chmod +x ci/push-docker.sh && ci/push-docker.sh
  unit-test:
    name: Unit tests
    needs: [docker]
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download repo
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
      - name: Run tests
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
  component-test:
    name: Component tests
    needs: [docker]
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
      - name: Execute component test
        run: chmod +x ci/component-test.sh && ci/component-test.sh
  perf-test:
    name: Performance tests
    needs: [docker]
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
      - name: Execute performance test
        run: chmod +x ci/performance-test.sh && ci/performance-test.sh
